### ISSUE TITLE
Типобезопасность идентификаторов.

### ISSUE THREAD

**Issue by olegromashin** [wixe/jsonserver.hs#5]
Сейчас для представления Id используется ньютайп для Int. Это не очень безопасно: если в каком-то юзкейсе у тебя будет несколько сущностей, то ты случайно можешь перепутать идентификаторы и испортить бд.
Здесь два варианта:
1. Создавать для каждой сущности свою тип-обёртку. Например:
newtype UserId = UserId { getUserId :: Int }
newtype CategoryId = CategoryId { getCategoryId :: Int }
2. Сделать тип с фантомной переменной. Этот вариант мне нравится больше,  почитать можно здесь: https://kowainik.github.io/posts/haskell-mini-patterns#phantom-type-parameters

**Comment by sirewix** [comment]
На данный момент есть два типа Id
1. `type Id = Int` используется в качестве аргументов для методов бд в `Model`.
2. `newtype Id = Id { unId :: Int }` с определенным FromQuery, используемый в качестве аргументов API  методов.
Единственную пользу более конкретной типизации я вижу только в случае если это будет один и тот же тип. В таком случае можно будет определить апи метод:
```
someCategoryMethod :: (... m) => CategoryId -> m AppResponse
someCategoryMethod cid = someDbMethod cid >>= doSmthWithResult
```
И соответственно db метод:
```
someDbMethod :: (... m) => CategoryId  -> m Category
```
В таком случае будет невозможно вызвать someDbMethod не сконструировав искуственно CategoryId, но это нарушит [разделение архитектуры на API и Model](https://github.com/wixe/jsonserver.hs/issues/1#issuecomment-711280770), придется в одном модуле (во избежание orphaned instances) определять функционал относящийся как с слою API так и к слою Db (`Model`)
Если же использовать разные ньютайпы то будет просто перепаковка из `API` (Query) ньютайпа в `Model` (Db) ньютайп, что особой типобезопасности не добавляет. К тому же API методы неправильно вызвать вообще нельзя, они вызываются только в `Entry` (роутер), и аргумент парсится напрямую из строки (единственное предназначение newtype Id)
С фантомным параметром подобные проблемы, плюс ко всему не понятно что должно быть параметром, когда у каждой сущности по три представления (Essential, Partial и Full)

Вот, не совсем понятно что от меня требуется

**Comment by olegromashin** [comment]
> К тому же API методы неправильно вызвать вообще нельзя

Я не это имел в виду. Например у тебя будет API, принимающий id трёх сущностей, что-то проверяющий и записывающий изменения в первую из них. По невнимательности в бд функцию можно передать id второй сущности, вместо первой, испортив данные. Сильная типизация языка позволяет наложить дополнительный уровень безопасности.
То что типы идентификаторов будут использоваться в разных компонентах не страшно, это не сущности, а более общие представления данных. Другое дело, что если делать для каждого типа свою обёртку, это будет выглядеть некрасиво, как по мне. На счёт варианта с фантомным параметром я потом пошарюсь по проекту, может появятся какие-то идеи.
В принципе можно не прорабатывать ишью, а оставить как обсуждение.

Поправь меня, если я где-то не так тебя понял)

**Comment by sirewix** [comment]
Посидел, подумал и все стало на свои места. Теперь дбшный Id (который был синонимом к инту) это ньютайп с фантомным параметром с соответствующими инстансами FromField и ToField (чтобы можно было удобно использовать его внутри рекордов). А api'шный Id теперь просто обертка `newtype QueryId a = QueryId (Id a)` (с общим для всех типов инстансом FromQuery). Таким образом, в API происходит распаковка `Id` из `QueryId` или из рекорда (если нужно несколько разнотиповых айдишников) и передача его (их) в нужный DB метод.
